name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  strongo_workflow:
    permissions:
      contents: write
    uses: strongo/cicd/.github/workflows/workflow.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    with:
      disable-version-bumping: true
